import cart from './modules/cart';
import getGoods from './modules/getGoods';
import search from './modules/search';
import smoothScroll from './modules/smoothScroll';
import slider from './modules/slider';
cart();
getGoods();
search();
slider();
smoothScroll();
